### ISSUE TITLE
Some issues..

### ISSUE THREAD

**Issue by trslvr** [occ-ai/obs-localvocal#49]
Hello, I would like to use this work, but I also have a few problems. I would be happy if you could help. Firstly, there are some issues with certain letters in the Turkish language, unfortunately. Secondly, even when I'm not speaking, it seems to be typing certain words on its own, and I couldn't prevent it in any way. I'm using the Whisper model as small, and it seems that the missing letters are probably ş, ğ, and ç. Thank you in advance.
![Screenshot_105](https://github.com/occ-ai/obs-localvocal/assets/115729746/cb7ddbf2-8b85-4ffe-8d24-5ab254d3f5c7)
![Screenshot_106](https://github.com/occ-ai/obs-localvocal/assets/115729746/b34b74b5-7e71-484d-a11a-5886929c117f)

**Comment by royshil** [comment]
thanks for the feedback
this UTF8 encoding problem is known..  #48 
I'm working on it and i can replicate in my windows machine.
i will resolve it very soon

**Comment by royshil** [comment]
@trslvr i fixed the issue
the special characters work for me
can you test https://github.com/occ-ai/obs-localvocal/actions/runs/6745930037?pr=47#artifacts ?
install the new plugin build on top of the old one

**Comment by trslvr** [comment]
Hello again, i replaced the file in the artifact with a new one and tried, but the issue still persists. Perhaps I couldn't perform the installation correctly. Secondly, it spontaneously generates sentences or displays [skip] when not being spoken.

**Comment by royshil** [comment]
@trslvr Yes the [skip] should also not appear anymore
So you must need to install the plugin again in a different way
Please copy the DLL file to the obs folder in `c:/program files`.

**Comment by royshil** [comment]
#47  confirmed to fix utf8 problems
